#!/bin/bash
set -e

# Fetches the latest stable and beta Flutter versions and writes them to
# sdk/versions.env so the "Check Flutter versions" workflow can track
# changes via pull requests.

releases_json=$(curl -s https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json)

# Get the latest version for a given channel (stable, beta, etc.)
get_latest_version_in_channel() {
    channel=$1
    channel_hash=$(echo "$releases_json" | jq -r '.current_release.'"$channel")
    version=$(echo "$releases_json" | jq -r --arg HASH "$channel_hash" \
        '.releases[] | select(.hash == $HASH).version')

    if [ -z "$version" ]; then
        echo "Error fetching latest version in channel $channel" >&2
        exit 1
    fi

    echo "$version"
}

stable_version=$(get_latest_version_in_channel "stable")
beta_version=$(get_latest_version_in_channel "beta")

echo "Latest stable version: $stable_version"
echo "Latest beta version: $beta_version"

# Write versions to a tracked file. The "Create Pull Request" step in the
# workflow picks up the diff and opens a PR when values change.
mkdir -p sdk
cat > sdk/versions.env <<EOF
# Auto-generated by scripts/update_flutter_versions.sh
# Do not edit by hand.
FLUTTER_STABLE_VERSION=${stable_version}
FLUTTER_BETA_VERSION=${beta_version}
EOF

echo "Wrote sdk/versions.env"
